### ISSUE TITLE
how to build it?

### ISSUE THREAD

**Issue by luckypoem** [sergeyfrolov/httpt#1]
can u explain clearly?
i wanna get the server side executable file and client side executable file

**Comment by sergeyfrolov** [comment]
Download latest golang, then
```
 git clone git@github.com:sergeyfrolov/httpt.git
  cd httpt/client/
  go get -d ./...
  go build .
  cd ../server/
  go get -d ./...
  go build .
```

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:client brite$  go get -d ./...
package httpt: unrecognized import path "httpt" (import path does not begin with hostname)
yudeMacBook-Air:client brite$ ls
client.go
yudeMacBook-Air:client brite$ nano client.go
(i modified "httpt" to be  "github.com/sergeyfrolov/httpt" )
yudeMacBook-Air:client brite$ go get -d ./...
yudeMacBook-Air:client brite$ ls
client.go
yudeMacBook-Air:client brite$ which client
yudeMacBook-Air:client brite$ which httpt
yudeMacBook-Air:client brite$ 

so where is the client side executable file? does i build successfully?

**Comment by sergeyfrolov** [comment]
After you gotten your dependncies with go get, you need to run `go build .`
