### ISSUE TITLE
How to send HTTP request from client to server?

### ISSUE THREAD

**Issue by creativepuzzle** [sergeyfrolov/httpt#2]
After build client and server, I tried to command "curl --location --request CONNECT 'localhost:4714'", but got this error "client.go:211: failed to read client hello: ". I am confused about how to use this program, can you give some instructions? Thanks

**Comment by sergeyfrolov** [comment]
Hey, sorry about the delay.
Try specifying the proxy address with `-x` and also specify the requested address, so if you wanted to request facebook.com, you'd execute
`curl -x http://localhost:4714 https://facebook.com`
